- README.md
Link to examples lead to 404. This changes points the link to the existing examples module.
> docs: Fixes broken link to examples

- examples/src/main/kotlin/org/jetbrains/kotlinx/spark/examples/Broadcasting.kt
- kotlin-spark-api/2.4/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/2.4/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
- kotlin-spark-api/3.0/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/3.0/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
Added a Kotlin wrapper for the function to broadcast read-only variables to the cluster. It works just as easily as `JavaSparkContext.broadcast()`
Created because of issue: https://github.com/JetBrains/kotlin-spark-api/issues/69
> feat: Adds broadcast function

- kotlin-spark-api/2.4/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/2.4/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
- kotlin-spark-api/3.0/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/3.0/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
Added java.sql.Date to knownDataTypes for both 2.4 and 3.0 including tests.
Added java.time.LocalDate and java.time.Instant to ENCODERS for 3.0 only (is not available in Spark 2.4) including tests.
> Add some missing Date encoders and data types

- examples/src/main/kotlin/org/jetbrains/kotlinx/spark/examples/Broadcasting.kt
- kotlin-spark-api/2.4/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/2.4/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
- kotlin-spark-api/3.0/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/3.0/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
Instead of calling 
```kotlin
spark.sparkContext.broadcast(
```
you can now simply call
```kotlin
spark.broadcast(
```
which matches some of the other helper functions in the API.
Aside from that there are a lot of cases where the `encoder<>()` function cannot find the encoder for a certain type like `Array<DoubleArray>` for instance. For these cases I added a fallback on the `JavaSparkContext.broadcast` function already present in Spark. This makes sure that at the `encoder<>()` method is attempted (so broadcasting Data classes still works fine), but if that fails it still has a backup solution.
Tests are included of course.
> Enhancement: Improved broadcasting

- kotlin-spark-api/2.4/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/2.4/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
- kotlin-spark-api/3.0/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/3.0/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
Added the last missing function wrappers for `KeyValueGroupedDataset` and `cogroup()` (all those shown as Java-specific) including some helper functions for `GroupState` like `getOrNull()` and delegation options for state.
Tests are included!
> Feature: more KeyValueGroupedDataset wrapper functions

- core/2.4/src/main/scala/org/apache/spark/sql/catalyst/KotlinReflection.scala
- core/3.0/src/main/scala/org/apache/spark/sql/KotlinReflection.scala
- kotlin-spark-api/2.4/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/2.4/src/main/kotlin/org/jetbrains/kotlinx/spark/api/Conversions.kt
- kotlin-spark-api/2.4/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
- kotlin-spark-api/3.0/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/3.0/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
Tuples of all sizes can now be encoded in Datasets because it doesn't use the `Encoders.tuple()` functions from Spark anymore.
I used the method similar to Kotlin data classes but with another wrapper and I edited the Scala files as well. 
I have had little experience with Scala, but borrowing code from other places in the file I managed to get the tests to work.
This continues the work from https://github.com/JetBrains/kotlin-spark-api/pull/79
And is discussed here https://github.com/JetBrains/kotlin-spark-api/issues/76
> Adds support for Tuple encoding

- core/3.0/src/main/scala/org/apache/spark/sql/KotlinReflection.scala
- kotlin-spark-api/3.0/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
As described by the issue here https://github.com/JetBrains/kotlin-spark-api/issues/86, this fixes the encoding for lists/arrays of complex objects.
For now it only works on 3.0, as I suspect the reason it doesn't work for 2.4 is due to https://github.com/JetBrains/kotlin-spark-api/issues/64 as well.
@asm0dey
> [Bugfix] Encoding Lists of data classes / tuples for 3.0

- kotlin-spark-api/2.4/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/2.4/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
- kotlin-spark-api/3.0/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/3.0/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
As discussed in the issue: https://github.com/JetBrains/kotlin-spark-api/issues/85
This adds the `selectTyped()` functions for `Dataset`s.
The results are mapped to `Pair`s, `Triple`s or `Arity`s for the respective amount of arguments given.
The creation of `TypedColumn`s is made a lot easier using a different pull request: https://github.com/JetBrains/kotlin-spark-api/pull/87, which I recommend to merge first, so that the temporary `col()` function in the tests here can be removed before merging :).
Note that on 2.4 the `selectTyped()` function cannot return a `Dataset` of a data class of an array. This is an encoding limitation which I mention here https://github.com/JetBrains/kotlin-spark-api/issues/64 as well.
> [Feat] Adds Dataset selectTyped functions

- kotlin-spark-api/2.4/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/2.4/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
- kotlin-spark-api/3.0/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/3.0/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
Just a couple of small things I came across while working with the library.
Firstly, `dataset.foreachPartition { }` has overload resolution ambiguity, so I added `forEachPartition {}` to the API.
Secondly, some functions (like `reduceGroups()`) return a `Dataset<Pair<K, V>>`, or the user creates a key/value like dataset themselves and then it might be useful to just take the keys or the values (I know I found it useful).
So I added `takeKeys()` and `takeValues()` for `Dataset<Pair>`, `Dataset<Tuple2>`, and `Dataset<Arity2>`. It's a small thing, but might improve readability.
Lastly, just like getting the columns using property references, it might also be useful to sort datasets using those, so I added the ability to do:
```kotlin
val sorted: Dataset<YourClass> = …
```
> Some more useful helper / wrapper functions

- core/3.0/src/main/scala/org/apache/spark/sql/KotlinReflection.scala
- kotlin-spark-api/2.4/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/2.4/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
- kotlin-spark-api/3.0/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/3.0/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
> Add enum support for `ApiV1Kt.generateEncoder`

- README.md
- kotlin-spark-api/2.4/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/2.4/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
- kotlin-spark-api/3.0/src/main/kotlin/org/jetbrains/kotlinx/spark/api/ApiV1.kt
- kotlin-spark-api/3.0/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
First of all, for consistency I added the `selectTyped()` function with a single column.
Secondly, I noticed when working with rows, it was very difficult to use selectTyped with it. I had to resort to notations like: 
```kotlin
val typedDs: Dataset<Int, String> = ds.selectTyped(col("a").`as`<Int>() as TypedColumn<Row, Int>, col("b").`as`<String>() as TypedColumn<Row, String> )
```
to even get it to compile (since ``` `as`()``` returns a `TypedColumn<Any, T>`.
So first I tried changing ``` `as`() ```, but that lead to notations like ```  `as`<Row, Int>()``` which is also less than ideal.
Next I changed `selectTyped()`, since that seems to be the only Dataset function that uses `TypedColumn`s at all. It also seems that the original `ds.select()` function doesn't care at all about the type …
> Better selectTyped behavior

- README.md
Hello! 👋
I have performed a few fixes in the documentation (`README.md`). See the list of changes below:
1. Correct artifact notation of the dependency in the pom.xml example (`kotlin-spark-api-3.0.0` → `kotlin-spark-api-3.0`)
2. Correct artifact notation of the dependency in the search query of Maven Central banner in 'Releases' section (`kotlin-spark-api-3.0.0` → `kotlin-spark-api-3.0`)
3. Correct version of artifact in Maven Central banner  (`1.0.1` → `1.0.2`)
4. Insignificant fixup in link to the issue 'SPARK-32530'
> fix: Perform fixes in README.md

- README.md
- kotlin-spark-api/3.2/src/main/kotlin/org/jetbrains/kotlinx/spark/api/SparkHelper.kt
As discussed here: https://github.com/JetBrains/kotlin-spark-api/issues/120
> Default master value to first check the system variables.

- core/3.2/src/main/scala/org/apache/spark/sql/KotlinReflection.scala
- core/3.2/src/main/scala/org/jetbrains/kotlinx/spark/extensions/DemoCaseClass.scala
- kotlin-spark-api/3.2/src/main/kotlin/org/jetbrains/kotlinx/spark/api/Encoding.kt
- kotlin-spark-api/3.2/src/test/kotlin/org/jetbrains/kotlinx/spark/api/EncodingTest.kt
as discovered in https://github.com/JetBrains/kotlin-spark-api/issues/146
> Rewrote product encoding to support scala case classes

- README.md
- jupyter/src/main/kotlin/org/jetbrains/kotlinx/spark/api/jupyter/Integration.kt
- jupyter/src/main/kotlin/org/jetbrains/kotlinx/spark/api/jupyter/SparkIntegration.kt
- jupyter/src/main/kotlin/org/jetbrains/kotlinx/spark/api/jupyter/SparkStreamingIntegration.kt
- jupyter/src/test/kotlin/org/jetbrains/kotlinx/spark/api/jupyter/JupyterTests.kt
- kotlin-spark-api/3.2/src/main/kotlin/org/jetbrains/kotlinx/spark/api/SparkSession.kt
Fixes the readme examples link.
Fixes printlns not working the second time a jupyter cell is run.
Attempted to fix when a cell with streaming is interrupted. This needs https://github.com/Kotlin/kotlin-jupyter/issues/369.
@asm0dey Also found one broken jupyter streaming test which I disabled for now. It works fine without jupyter, but you know how difficult it is to test streaming... We can leave it disabled for the release and look at it later since Jupyter support is still experimental for now.
> Readme streaming (1.1.0 release)

- README.md
Also trying new pull requesting method :), including a milestone and targeting main instead.
@asm0dey
> updated readme for contribution guide

- core/src/main/scala/org/apache/spark/sql/KotlinReflection.scala
- kotlin-spark-api/src/main/kotlin/org/jetbrains/kotlinx/spark/api/Encoding.kt
- kotlin-spark-api/src/test/kotlin/org/jetbrains/kotlinx/spark/api/EncodingTest.kt
https://github.com/Kotlin/kotlin-spark-api/issues/170
> [Fix] Encoding isSomething names in data classes

- kotlin-spark-api/src/main/kotlin/org/jetbrains/kotlinx/spark/api/Seq.kt
- kotlin-spark-api/src/test/kotlin/org/jetbrains/kotlinx/spark/api/ApiTest.kt
https://github.com/Kotlin/kotlin-spark-api/issues/163
> [Feature] Seq of functions

- buildSrc/src/main/kotlin/Versions.kt
- jupyter/src/test/kotlin/org/jetbrains/kotlinx/spark/api/jupyter/JupyterTests.kt
Fixes https://github.com/Kotlin/kotlin-spark-api/issues/199.
Seems that the Kotlin Jupyter API has been updated to support Java 8 since the last time I checked :) This PR makes it so our integration module is downgraded to Java 8 as well.
> Set Jupyter version to Java 8

- buildSrc/src/main/kotlin/Versions.kt
looks like kotlin 1.9.0 still causes issues, but bumps to 1.8.20 are fine
> Version bumps
